version: '2'
services:
    donit-https:
        image: abiosoft/caddy
        ports: 
        - "443:443"
        - "80:80"
        volumes:
        - ./Caddyfile:/etc/Caddyfile
        - ${HOME}/.caddy:/root/.caddy
    donit-web:
        build: ./web
        volumes:
        - /var/www/www.donit.xyz:/public
    donit-test:
        build: ./web
        volumes:
        - /var/www/test.donit.xyz:/public
    donit-database:
        image: cockroachdb/cockroach:beta-20170112
        volumes: 
        - /var/lib/cockroach/data1:/cockroach/cockroach-data
        command: [start,--insecure,--host=donit-database,--logtostderr]
    donit-api:
        image: jetty
        volumes: 
        - /var/www/api.donit.xyz:/var/lib/jetty/webapps
        depends_on:
        - donit-database
